classdef ExitSlit < mic.Base
    
    properties
        
        
        % These are the UI for activating the hardware that gives the 
        % software real data
        
        % {mic.ui.device.GetSetLogical 1x1}
        uiCommExitSlit
       
        % {mic.ui.device.GetSetNumber 1x1}
        uiStage1
        uiStage2
        uiStage3
        uiStage4
        uiGap
                
        uiPositionRecaller
        
    end
    
    properties (Access = private)
        
        clock
        
        hPanel
        
        
        dWidthPanelMotors = 710
        dHeightPanelMotors = 100
        
        dWidthName = 100

        dWidthVal = 40
        dWidthDest = 40
        dWidthPadName = 5
        dWidthPadStep = 0
        dWidthStep = 30
        dWidthPadUnitEncoder = 5
        dWidthUnitTemp = 100
                
        dWidthButton = 55
        
    end
    
    properties (SetAccess = private)
        
        cName = 'exit-slit'
        dWidth = 670
        dHeight = 140
        
        % {bl12014.Hardware 1x1}
        hardware
    end
    
    methods
        
        function this = ExitSlit(varargin)
            for k = 1 : 2: length(varargin)
                this.msg(sprintf('passed in %s', varargin{k}), this.u8_MSG_TYPE_VARARGIN_PROPERTY);
                if this.hasProp( varargin{k})
                    this.msg(sprintf(' settting %s', varargin{k}), this.u8_MSG_TYPE_VARARGIN_SET);
                    this.(varargin{k}) = varargin{k + 1};
                end
            end
            
            if ~isa(this.hardware, 'bl12014.Hardware')
                error('hardware must be bl12014.Hardware');
            end
            
            
            if ~isa(this.clock, 'mic.Clock') && ~isa(this.clock, 'mic.ui.Clock')
                error('clock must be mic.Clock | mic.ui.Clock');
            end
            
            this.init();
        
        end
        
        function cec = getSaveLoadProps(this)
            
           cec = {...
               'uiStage1', ...
               'uiStage2', ...
               'uiStage3', ...
               'uiStage4' ...
           };
            
        end
        function st = save(this)
            
            cecProps = this.getSaveLoadProps();
            
            st = struct();
            for n = 1 : length(cecProps)
                cProp = cecProps{n};
                st.(cProp) = this.(cProp).save();
            end
            
            
            
        end
        
        
        function load(this, st)
            
            cecProps = this.getSaveLoadProps();
            for n = 1 : length(cecProps)
                cProp = cecProps{n};
               if isfield(st, cProp)
               	this.(cProp).load(st.(cProp))
               end
            end
            
        end
        
       

        
        function build(this, hParent, dLeft, dTop)
                        
            this.hPanel = uipanel(...
                'Parent', hParent,...
                'Units', 'pixels',...
                'Title', 'Exit Slit',...
                'Clipping', 'on',...
                'Position', mic.Utils.lt2lb([ ...
                dLeft ...
                dTop ...
                this.dWidth ...
                this.dHeight], hParent) ...
            );
        
            dLeft = 0;
            dTop = 15;
            dSep = 30;
                       

            this.uiGap.build(this.hPanel, dLeft, dTop);
          
            dTop = 70;
            
            dLeftCol1 = 0;
            dLeftCol2 = 350;
            dSep = 30;
            
            this.uiStage1.build(this.hPanel, dLeftCol1, dTop);
            dTop = dTop + dSep;
            
            this.uiStage2.build(this.hPanel, dLeftCol1, dTop);
            dTop = 70;
            
            this.uiStage3.build(this.hPanel, dLeftCol2, dTop);
            dTop = dTop + dSep;
            
            this.uiStage4.build(this.hPanel, dLeftCol2, dTop);
        end
        
        function delete(this)
            
            delete(this.uiStage1);
            delete(this.uiStage2);
            delete(this.uiStage3);
            delete(this.uiStage4);
            delete(this.uiCommExitSlit);
            delete(this.uiGap);
            
        end    
        
        
        
    end
    
    methods (Access = private)
        
         
         
        
         
        function ce = getUiStageCommonProps(this)
             ce = {...
                'dWidthName', this.dWidthName, ...
                'dWidthPadName', this.dWidthPadName, ...
                'dWidthVal', this.dWidthVal, ...
                'dWidthDest', this.dWidthDest, ...
                'lShowInitButton', false, ...
                'lShowLabels', false, ...
                'lShowRange', false, ...
                'lShowStores', false, ...
                'lShowZero', false, ...
                'lShowRel', false, ...
                'lShowPlay', true, ...
                'lShowStepPos', true, ...
                'lShowUnit', false, ...
                'lShowStepNeg', true, ...
                'dWidthPadStep', this.dWidthPadStep, ...
                'lDisableMoveToDestOnDestEnter', false, ...
                'dWidthStep', this.dWidthStep ... 
           };
             
        end
               
        
        function initUiStage1(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-set-number', ...
                'config-exit-slit-blade.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
        
            device = bl12014.device.GetSetNumberFromExitSlitObject(...
                @() this.hardware.getExitSlit(), ...
                bl12014.device.GetSetNumberFromExitSlitObject.cPROP_MOTOR_UPPER_OUT);
            
            
            ceProps = this.getUiStageCommonProps();
            this.uiStage1 = mic.ui.device.GetSetNumber(...
                'clock', this.clock, ...
                ceProps{:}, ...
                'fhGet', @() device.get(), ...
                'fhSet', @(dVal) device.set(dVal), ...
                'fhIsReady', @() device.isReady(), ...
                'fhStop', @() device.stop(), ...
                'fhIsVirtual', @() false, ...
                'lUseFunctionCallbacks', true, ...
                'lShowLabels', false, ...
                'cName', sprintf('%s-upper-outboard', this.cName), ...
                'config', uiConfig, ...
                'cLabel', 'Upper Out (6) (um)' ...
            );
        end
        
        function initUiStage2(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-set-number', ...
                'config-exit-slit-blade.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
        
            device = bl12014.device.GetSetNumberFromExitSlitObject(...
                @() this.hardware.getExitSlit(), ...
                bl12014.device.GetSetNumberFromExitSlitObject.cPROP_MOTOR_LOWER_OUT);

            
            ceProps = this.getUiStageCommonProps();
            this.uiStage2 = mic.ui.device.GetSetNumber(...
                'clock', this.clock, ...
                ceProps{:}, ...
                'fhGet', @() device.get(), ...
                'fhSet', @(dVal) device.set(dVal), ...
                'fhIsReady', @() device.isReady(), ...
                'fhStop', @() device.stop(), ...
                'fhIsVirtual', @() false, ...
                'lUseFunctionCallbacks', true, ...
                'cName', sprintf('%s-lower-outboard', this.cName), ...
                'config', uiConfig, ...
                'cLabel', 'Lower Out (7) (um)' ...
            );
        end
        
        function initUiStage3(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-set-number', ...
                'config-exit-slit-blade.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
        
        device = bl12014.device.GetSetNumberFromExitSlitObject(...
                @() this.hardware.getExitSlit(), ...
                bl12014.device.GetSetNumberFromExitSlitObject.cPROP_MOTOR_UPPER_IN);
            
            
            ceProps = this.getUiStageCommonProps();
            this.uiStage3 = mic.ui.device.GetSetNumber(...
                'clock', this.clock, ...
                ceProps{:}, ...
                'fhGet', @() device.get(), ...
                'fhSet', @(dVal) device.set(dVal), ...
                'fhIsReady', @() device.isReady(), ...
                'fhStop', @() device.stop(), ...
                'fhIsVirtual', @() false, ...
                'lUseFunctionCallbacks', true, ...
                'cName', sprintf('%s-upper-inboard', this.cName), ...
                'config', uiConfig, ...
                'lShowLabels', false, ...
                'cLabel', 'Upper In (4) (um)' ...
            );
        end
        
        function initUiStage4(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-set-number', ...
                'config-exit-slit-blade.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
        
        device = bl12014.device.GetSetNumberFromExitSlitObject(...
                @() this.hardware.getExitSlit(), ...
                bl12014.device.GetSetNumberFromExitSlitObject.cPROP_MOTOR_LOWER_IN);
            
            
            ceProps = this.getUiStageCommonProps();
            this.uiStage4 = mic.ui.device.GetSetNumber(...
                'clock', this.clock, ...
                ceProps{:}, ...
                'fhGet', @() device.get(), ...
                'fhSet', @(dVal) device.set(dVal), ...
                'fhIsReady', @() device.isReady(), ...
                'fhStop', @() device.stop(), ...
                'fhIsVirtual', @() false, ...
                'lUseFunctionCallbacks', true, ...
                'cName', sprintf('%s-lower-inboard', this.cName), ...
                'config', uiConfig, ...
                'cLabel', 'Lower In (5) (um)' ...
            );
        end
        
        
        function initUiGap(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-set-number', ...
                'config-gap-of-exit-slit.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
        
            device = bl12014.device.GetSetNumberFromExitSlitObject(...
                @() this.hardware.getExitSlit(), ...
                bl12014.device.GetSetNumberFromExitSlitObject.cPROP_GAP);
            
            
            ceProps = this.getUiStageCommonProps();
            this.uiGap = mic.ui.device.GetSetNumber(...
                'clock', this.clock, ...
                ceProps{:}, ...
                'fhGet', @() device.get(), ...
                'fhSet', @(dVal) device.set(dVal), ...
                'fhIsReady', @() device.isReady(), ...
                'fhStop', @() device.stop(), ...
                'fhIsVirtual', @() false, ...
                'lUseFunctionCallbacks', true, ...
                'lShowLabels', true, ...
                'lShowStores', true, ...
                'dWidthStores', 150, ...
                'cName', sprintf('%s-gap', this.cName), ...
                'config', uiConfig, ...
                'cLabel', 'Gap (um)' ...
            );
        end
        
        
        
        
        
        
        
        
        
        function initUiPositionRecaller(this)
            
            cDirThis = fileparts(mfilename('fullpath'));
            cPath = fullfile(cDirThis, '..', '..', 'save', 'position-recaller');
            this.uiPositionRecaller = mic.ui.common.PositionRecaller(...
                'cConfigPath', cPath, ... 
                'cName', [this.cName, '-position-recaller'], ...
                'hGetCallback', @this.getStageValues, ...
                'hSetCallback', @this.setStageValues ...
            );
        end
        
        
        
        
        

        function init(this)
            this.msg('init');
            this.initUiStage1();
            this.initUiStage2();
            this.initUiStage3();
            this.initUiStage4();
            this.initUiGap();
            
            % this.initUiPositionRecaller();
        end
        
        
        % Return list of values from your app
        function dValues = getStageValues(this)
            dValues = [...
                this.uiStage1.getValRaw(), ...
                this.uiStage2.getValRaw(), ...
                this.uiStage3.getValRaw(), ...
                this.uiStage4.getValRaw() ...
            ];
        end
        
        % Set recalled values into your app
        function setStageValues(this, dValues)
            this.uiStage1.setDestRaw(dValues(1));
            this.uiStage2.setDestRaw(dValues(2));
            this.uiStage3.setDestRaw(dValues(3));
            this.uiStage4.setDestRaw(dValues(4));
        end
        
        
        
    end
    
    
end

