classdef HeightSensor < mic.Base
    
    properties
        
        % README
        % Eventually may add UI for tiltX, tiltY, and avgZ

        % {mic.ui.device.GetNumber 1x1}}
        uiChannel1
        
        % {mic.ui.device.GetNumber 1x1}}
        uiChannel2
        
        % {mic.ui.device.GetNumber 1x1}}
        uiChannel3
        
        % {mic.ui.device.GetNumber 1x1}}
        uiChannel4
        
        % {mic.ui.device.GetNumber 1x1}}
        uiChannel5
        
        % {mic.ui.device.GetNumber 1x1}}
        uiChannel6
        
        
    end
    
    properties (SetAccess = private)
        
        dWidth = 600
        dHeight = 220
        
        cName = 'Height Sensors'
        
    end
    
    properties (Access = private)
        
        clock
        
        hPanel
        
        dWidthName = 70
        dWidthUnit = 80
        dWidthVal = 75
        dWidthPadUnit = 277
        
        configStageY
        configMeasPointVolts
        
    end
    
    methods
        
        function this = HeightSensor(varargin)
            for k = 1 : 2: length(varargin)
                % this.msg(sprintf('passed in %s', varargin{k}));
                if this.hasProp( varargin{k})
                    this.msg(sprintf(' settting %s', varargin{k}), 3);
                    this.(varargin{k}) = varargin{k + 1};
                end
            end
            
            this.init();
        
        end
        
        
        function turnOn(this)
            
            this.uiChannel1.turnOn();
            this.uiChannel2.turnOn();
            this.uiChannel3.turnOn();
            this.uiChannel4.turnOn();
            this.uiChannel5.turnOn();
            this.uiChannel6.turnOn();
            
            
            
            
        end
        
        function turnOff(this)
            this.uiChannel1.turnOff();
            this.uiChannel2.turnOff();
            this.uiChannel3.turnOff();
            this.uiChannel4.turnOff();
            this.uiChannel5.turnOff();
            this.uiChannel6.turnOff();
            
            
            
        end
        
        function build(this, hParent, dLeft, dTop)
            
            this.hPanel = uipanel(...
                'Parent', hParent,...
                'Units', 'pixels',...
                'Title', 'Height Sensor',...
                'Clipping', 'on',...
                'Position', mic.Utils.lt2lb([ ...
                dLeft ...
                dTop ...
                this.dWidth ...
                this.dHeight], hParent) ...
            );
        
			drawnow;            

            dTop = 20;
            dLeft = 10;
            dSep = 30;
            
            this.uiChannel1.build(this.hPanel, dLeft, dTop);
            dTop = dTop + 15 + dSep;
            
            this.uiChannel2.build(this.hPanel, dLeft, dTop);
            dTop = dTop + dSep;
            
            this.uiChannel3.build(this.hPanel, dLeft, dTop);
            dTop = dTop + dSep;
            
            this.uiChannel4.build(this.hPanel, dLeft, dTop);
            dTop = dTop + dSep;
            
            this.uiChannel5.build(this.hPanel, dLeft, dTop);
            dTop = dTop + dSep;
            
            this.uiChannel6.build(this.hPanel, dLeft, dTop);
            dTop = dTop + dSep;
            
            
        end
        
        function delete(this)
            
            this.msg('delete');
                        
            % Delete the figure
            
            if ishandle(this.hPanel)
                delete(this.hPanel);
            end
            
            
        end    
        
        
    end
    
    methods (Access = private)
                
         
        function initUiChannel1(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-number', ...
                'config-height-sensor-channel.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiChannel1 = mic.ui.device.GetNumber(...
                'clock', this.clock, ...
                'dWidthName', this.dWidthName, ...
                'dWidthUnit', this.dWidthUnit, ...
                'dWidthVal', this.dWidthVal, ...
                'dWidthPadUnit', this.dWidthPadUnit, ...
                'cName', 'height-sensor-1', ...
                'config', uiConfig, ...
                'cLabel', '1' ...
            );
        end
        
        function initUiChannel2(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-number', ...
                'config-height-sensor-channel.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiChannel2 = mic.ui.device.GetNumber(...
                'clock', this.clock, ...
                'dWidthName', this.dWidthName, ...
                'dWidthUnit', this.dWidthUnit, ...
                'dWidthVal', this.dWidthVal, ...
                'dWidthPadUnit', this.dWidthPadUnit, ...
                'cName', 'height-sensor-2', ...
                'lShowLabels', false, ...
                'config', uiConfig, ...
                'cLabel', '2' ...
            );
        end
        
        function initUiChannel3(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-number', ...
                'config-height-sensor-channel.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiChannel3 = mic.ui.device.GetNumber(...
                'clock', this.clock, ...
                'dWidthName', this.dWidthName, ...
                'dWidthUnit', this.dWidthUnit, ...
                'dWidthVal', this.dWidthVal, ...
                'dWidthPadUnit', this.dWidthPadUnit, ...
                'cName', 'height-sensor-3', ...
                'lShowLabels', false, ...
                'config', uiConfig, ...
                'cLabel', '3' ...
            );
        end
        
        function initUiChannel4(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-number', ...
                'config-height-sensor-channel.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiChannel4 = mic.ui.device.GetNumber(...
                'clock', this.clock, ...
                'dWidthName', this.dWidthName, ...
                'dWidthUnit', this.dWidthUnit, ...
                'dWidthVal', this.dWidthVal, ...
                'dWidthPadUnit', this.dWidthPadUnit, ...
                'cName', 'height-sensor-4', ...
                'lShowLabels', false, ...
                'config', uiConfig, ...
                'cLabel', '4' ...
            );
        end
        
        function initUiChannel5(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-number', ...
                'config-height-sensor-channel.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiChannel5 = mic.ui.device.GetNumber(...
                'clock', this.clock, ...
                'dWidthName', this.dWidthName, ...
                'dWidthUnit', this.dWidthUnit, ...
                'dWidthVal', this.dWidthVal, ...
                'dWidthPadUnit', this.dWidthPadUnit, ...
                'cName', 'height-sensor-5', ...
                'lShowLabels', false, ...
                'config', uiConfig, ...
                'cLabel', '5' ...
            );
        end
        
        function initUiChannel6(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-number', ...
                'config-height-sensor-channel.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiChannel6 = mic.ui.device.GetNumber(...
                'clock', this.clock, ...
                'dWidthName', this.dWidthName, ...
                'dWidthUnit', this.dWidthUnit, ...
                'dWidthVal', this.dWidthVal, ...
                'dWidthPadUnit', this.dWidthPadUnit, ...
                'cName', 'height-sensor-6', ...
                'lShowLabels', false, ...
                'config', uiConfig, ...
                'cLabel', '6' ...
            );
        end
        
       
        
        
        
        function init(this)
            this.msg('init()');
            this.initUiChannel1();
            this.initUiChannel2();
            this.initUiChannel3();
            this.initUiChannel4();
            this.initUiChannel5();
            this.initUiChannel6();
            
            
        end
        
        
        
    end
    
    
end

