classdef M141 < mic.Base
    
    properties
        
        % {mic.ui.device.GetSetLogical 1x1}
        uiCommSmarActMcsM141
        

        
        % {mic.ui.device.GetSetNumber 1x1}}
        uiStageX
        
        % {mic.ui.device.GetSetNumber 1x1}}
        uiStageTiltX
        
        % {mic.ui.device.GetSetNumber 1x1}}
        uiStageTiltY
        
        % {mic.ui.device.GetNumber 1x1}
        uiCurrent
        
    end
    
    properties (Access = private)
        
        clock
        dWidth = 590
        dHeight = 225
        
        configStageY
        configMeasPointVolts
        
        hPanel
        
        % {bl12014.Hardware 1x1}
        hardware
        
    end
    
    properties (SetAccess = private)
        
        cName = 'm141-'
    end
    
    methods
        
        function this = M141(varargin)
            for k = 1 : 2: length(varargin)
                this.msg(sprintf('passed in %s', varargin{k}), this.u8_MSG_TYPE_VARARGIN_PROPERTY);
                if this.hasProp( varargin{k})
                    this.msg(sprintf(' settting %s', varargin{k}), this.u8_MSG_TYPE_VARARGIN_SET);
                    this.(varargin{k}) = varargin{k + 1};
                end
            end
            
            if ~isa(this.hardware, 'bl12014.Hardware')
                error('hardware must be bl12014.Hardware');
            end
            
            
            if ~isa(this.clock, 'mic.Clock') && ~isa(this.clock, 'mic.ui.Clock')
                error('clock must be mic.Clock | mic.ui.Clock');
            end
            
            this.init();
        
        end
        
    
        
                
        function build(this, hParent, dLeft, dTop)
            
            
            this.hPanel = uipanel(...
                'Parent', hParent,...
                'Units', 'pixels',...
                'Title', 'M141',...
                'Clipping', 'on',...
                'Position', mic.Utils.lt2lb([ ...
                dLeft ...
                dTop ...
                this.dWidth ...
                this.dHeight], hParent) ...
            );
        
            dLeft = 0;
            dTop = 15;
            dSep = 30;
            
             
            this.uiStageX.build(this.hPanel, dLeft, dTop);
            dTop = dTop + 15 + dSep;
            
            
            this.uiStageTiltX.build(this.hPanel, dLeft, dTop);
            dTop = dTop + dSep;
            
            this.uiStageTiltY.build(this.hPanel, dLeft, dTop);
            dTop = dTop + dSep;
            
            this.uiCurrent.build(this.hPanel, dLeft, dTop);
            dTop = dTop + dSep;

            
        end
        
        
       
        
        
        function delete(this)
            
            
            
        end   
        
        function st = save(this)
            st = struct();
            st.uiStageX = this.uiStageX.save();
        end
        
        function load(this, st)
            if isfield(st, 'uiStageY')
                this.uiStageX.load(st.uiStageX)
            end
        end
        
        
    end
    
    methods (Access = private)
        
         function onFigureCloseRequest(this, src, evt)
            this.msg('M141Control.closeRequestFcn()');
            delete(this.hFigure);
            this.hFigure = [];
         end
        
         
        function initUiStageX(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-set-number', ...
                'config-m141-stage-x.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiStageX = mic.ui.device.GetSetNumber(...
                'clock', this.clock, ...
                'cName', sprintf('%s-x', this.cName), ...
                'config', uiConfig, ...
                'lShowInitButton', true, ...
                'fhGet', @() this.hardware.getSmarActM141().getAxisPosition(0), ...
                'fhSet', @(dVal) this.hardware.getSmarActM141().moveAxisAbsolute(0, dVal), ...
                'fhIsReady', @() this.hardware.getSmarActM141().getAxisIsReady(0), ...
                'fhStop', @() this.hardware.getSmarActM141().stopAxisMove(0), ...
                'fhInitialize', @() mic.Utils.evalAll(...
                    @() this.hardware.getSmarActM141().initializeAxis(0) ...
                ), ... % wrap because fhInitialize doesn't expect a return but initializeAxis returns something
                'fhIsInitialized', @() this.hardware.getSmarActM141.getAxisIsInitialized(0), ...
                'fhIsVirtual', @() false, ...
                'lUseFunctionCallbacks', true, ...
                'cLabel', 'X' ...
            );
        end
        
        function initUiStageTiltX(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-set-number', ...
                'config-m141-stage-tilt-x.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiStageTiltX = mic.ui.device.GetSetNumber(...
                'clock', this.clock, ...
                'lShowLabels', false, ...
                'cName', sprintf('%s-tilt-x', this.cName), ...
                'config', uiConfig, ...
                'lShowInitButton', true, ...
                'fhGet', @() this.hardware.getSmarActM141().getAxisPosition(1), ...
                'fhSet', @(dVal) this.hardware.getSmarActM141().moveAxisAbsolute(1, dVal), ...
                'fhIsReady', @() this.hardware.getSmarActM141().getAxisIsReady(1), ...
                'fhStop', @() this.hardware.getSmarActM141().stopAxisMove(1), ...
                'fhInitialize', @() mic.Utils.evalAll(...
                    @() this.hardware.getSmarActM141().initializeAxis(1) ...
                ), ... % wrap because fhInitialize doesn't expect a return but initializeAxis returns something
                'fhIsInitialized', @() this.hardware.getSmarActM141.getAxisIsInitialized(1), ...
                'fhIsVirtual', @() false, ...
                'lUseFunctionCallbacks', true, ...
                'cLabel', 'Tilt X' ...
            );
        end
        
        function initUiStageTiltY(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-set-number', ...
                'config-m141-stage-tilt-y.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiStageTiltY = mic.ui.device.GetSetNumber(...
                'clock', this.clock, ...
                'lShowLabels', false, ...
                'cName', sprintf('%s-tilt-y', this.cName), ...
                'config', uiConfig, ...
                'lShowInitButton', true, ...
                'fhGet', @() this.hardware.getSmarActM141().getAxisPosition(2), ...
                'fhSet', @(dVal) this.hardware.getSmarActM141().moveAxisAbsolute(2, dVal), ...
                'fhIsReady', @() this.hardware.getSmarActM141().getAxisIsReady(2), ...
                'fhStop', @() this.hardware.getSmarActM141().stopAxisMove(2), ...
                'fhInitialize', @() mic.Utils.evalAll(...
                    @() this.hardware.getSmarActM141().initializeAxis(2) ...
                ), ... % wrap because fhInitialize doesn't expect a return but initializeAxis returns something
                'fhIsInitialized', @() this.hardware.getSmarActM141.getAxisIsInitialized(2), ...
                'fhIsVirtual', @() false, ...
                'lUseFunctionCallbacks', true, ...
                'cLabel', 'Tilt Y' ...
            );
        end
        
                
        function initUiCurrent(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-number', ...
                'config-m141-current.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
        
            this.uiCurrent = mic.ui.device.GetNumber(...
                'clock', this.clock, ...
                'cName', [this.cName, 'current'], ... 
                'config', uiConfig, ...
                'cLabel', 'Current', ...
                'dWidthPadUnit', 277, ...
                'lShowInitButton', true, ...
                'lShowLabels', false, ...
                'fhGet', @() this.hardware.getDataTranslation().getScanDataOfChannel(32), ...
                'fhIsVirtual', @() false, ...
                'lUseFunctionCallbacks', true ...
            );
        end
        
       
        
        function init(this)
            
            this.msg('init');
            this.initUiStageX();
            this.initUiStageTiltX();
            this.initUiStageTiltY();
            this.initUiCurrent();
        end
        
        
        
    end
    
    
end

