classdef Mod3TempSensors < mic.Base
    
    properties

        % {mic.ui.device.GetNumber 1x1}}
        uiReticleCam1
        
        % {mic.ui.device.GetNumber 1x1}}
        uiReticleCam2
        
        % {mic.ui.device.GetNumber 1x1}}
        uiFiducialCam1
        
        % {mic.ui.device.GetNumber 1x1}}
        uiFiducialCam2
        
        % {mic.ui.device.GetNumber 1x1}}
        uiFrame1
        
        % {mic.ui.device.GetNumber 1x1}}
        uiFrame2
        
        % {mic.ui.device.GetNumber 1x1}}
        uiFrame3
        
        % {mic.ui.device.GetNumber 1x1}}
        uiFrame4
        
        % {mic.ui.device.GetNumber 1x1}}
        uiFrame5
        
        % {mic.ui.device.GetNumber 1x1}}
        uiFrame6
        
        
        
    end
    
    properties (SetAccess = private)
        
        dWidth = 320
        dHeight = 340
        
        cName = 'Mod3TempSensors'
        
    end
    
    properties (Access = private)
        
        clock
        
        hPanel
        
        dWidthName = 80
        dWidthUnit = 90
        dWidthVal = 50
        
        configStageY
        configMeasPointVolts
        
    end
    
    methods
        
        function this = Mod3TempSensors(varargin)
            for k = 1 : 2: length(varargin)
                this.msg(sprintf('passed in %s', varargin{k}), this.u8_MSG_TYPE_VARARGIN_PROPERTY);
                if this.hasProp( varargin{k})
                    this.msg(sprintf(' settting %s', varargin{k}), this.u8_MSG_TYPE_VARARGIN_SET);
                    this.(varargin{k}) = varargin{k + 1};
                end
            end
            
            this.init();
        
        end
        
        
        function turnOn(this)
            
            this.uiReticleCam1.turnOn();
            this.uiReticleCam2.turnOn();
            this.uiFiducialCam1.turnOn();
            this.uiFiducialCam2.turnOn();
            this.uiFrame1.turnOn();
            this.uiFrame2.turnOn();
            this.uiFrame3.turnOn();
            this.uiFrame4.turnOn();
            this.uiFrame5.turnOn();
            this.uiFrame6.turnOn();
            
            
            
        end
        
        function turnOff(this)
            this.uiReticleCam1.turnOff();
            this.uiReticleCam2.turnOff();
            this.uiFiducialCam1.turnOff();
            this.uiFiducialCam2.turnOff();
            this.uiFrame1.turnOff();
            this.uiFrame2.turnOff();
            this.uiFrame3.turnOff();
            this.uiFrame4.turnOff();
            this.uiFrame5.turnOff();
            this.uiFrame6.turnOff();
            
        end
        
        function build(this, hParent, dLeft, dTop)
            
            this.hPanel = uipanel(...
                'Parent', hParent,...
                'Units', 'pixels',...
                'Title', 'Mod3 Temp Sensors',...
                'Clipping', 'on',...
                'Position', mic.Utils.lt2lb([ ...
                dLeft ...
                dTop ...
                this.dWidth ...
                this.dHeight], hParent) ...
            );
        
			drawnow;            

            dTop = 20;
            dLeft = 10;
            dSep = 30;
            
            this.uiReticleCam1.build(this.hPanel, dLeft, dTop);
            dTop = dTop + 15 + dSep;
            
            this.uiReticleCam2.build(this.hPanel, dLeft, dTop);
            dTop = dTop + dSep;
            
            this.uiFiducialCam1.build(this.hPanel, dLeft, dTop);
            dTop = dTop + dSep;
            
            this.uiFiducialCam2.build(this.hPanel, dLeft, dTop);
            dTop = dTop + dSep;
            
            this.uiFrame1.build(this.hPanel, dLeft, dTop);
            dTop = dTop + dSep;
            
            this.uiFrame2.build(this.hPanel, dLeft, dTop);
            dTop = dTop + dSep;
            
            this.uiFrame3.build(this.hPanel, dLeft, dTop);
            dTop = dTop + dSep;
            
            this.uiFrame4.build(this.hPanel, dLeft, dTop);
            dTop = dTop + dSep;
            
            this.uiFrame5.build(this.hPanel, dLeft, dTop);
            dTop = dTop + dSep;
            
            this.uiFrame6.build(this.hPanel, dLeft, dTop);
            dTop = dTop + dSep;
            
           
           
            
        end
        
        function delete(this)
            
            this.msg('delete');
                        
            % Delete the figure
            
            if ishandle(this.hPanel)
                delete(this.hPanel);
            end
            
            
        end    
        
        
    end
    
    methods (Access = private)
                
         
        function initUiReticleCam1(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-number', ...
                'config-mod3-temp-sensor-pt1000.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiReticleCam1 = mic.ui.device.GetNumber(...
                'clock', this.clock, ...
                'dWidthName', this.dWidthName, ...
                'dWidthUnit', this.dWidthUnit, ...
                'dWidthVal', this.dWidthVal, ...
                'cName', 'mod3-temp-sensor-reticle-cam-1', ...
                'config', uiConfig, ...
                'cLabel', 'Reticle Cam 1' ...
            );
        end
        
        function initUiReticleCam2(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-number', ...
                'config-mod3-temp-sensor-pt1000.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiReticleCam2 = mic.ui.device.GetNumber(...
                'clock', this.clock, ...
                'dWidthName', this.dWidthName, ...
                'dWidthUnit', this.dWidthUnit, ...
                'dWidthVal', this.dWidthVal, ...
                'cName', 'mod3-temp-sensor-reticle-cam-2', ...
                'lShowLabels', false, ...
                'config', uiConfig, ...
                'cLabel', 'Reticle Cam 2' ...
            );
        end
        
        function initUiFiducialCam1(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-number', ...
                'config-mod3-temp-sensor-pt1000.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiFiducialCam1 = mic.ui.device.GetNumber(...
                'clock', this.clock, ...
                'dWidthName', this.dWidthName, ...
                'dWidthUnit', this.dWidthUnit, ...
                'dWidthVal', this.dWidthVal, ...
                'cName', 'mod3-temp-sensor-fiducial-cam-1', ...
                'lShowLabels', false, ...
                'config', uiConfig, ...
                'cLabel', 'Fiducial Cam 1' ...
            );
        end
        
        function initUiFiducialCam2(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-number', ...
                'config-mod3-temp-sensor-pt1000.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiFiducialCam2 = mic.ui.device.GetNumber(...
                'clock', this.clock, ...
                'dWidthName', this.dWidthName, ...
                'dWidthUnit', this.dWidthUnit, ...
                'dWidthVal', this.dWidthVal, ...
                'cName', 'mod3-temp-sensor-fiducial-cam-2', ...
                'lShowLabels', false, ...
                'config', uiConfig, ...
                'cLabel', 'Fiducial Cam 2' ...
            );
        end
        
        function initUiFrame1(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-number', ...
                'config-mod3-temp-sensor-pt100.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiFrame1 = mic.ui.device.GetNumber(...
                'clock', this.clock, ...
                'dWidthName', this.dWidthName, ...
                'dWidthUnit', this.dWidthUnit, ...
                'dWidthVal', this.dWidthVal, ...
                'cName', 'mod3-temp-sensor-frame-1', ...
                'lShowLabels', false, ...
                'config', uiConfig, ...
                'cLabel', 'Frame 1' ...
            );
        end
        
        function initUiFrame2(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-number', ...
                'config-mod3-temp-sensor-pt100.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiFrame2 = mic.ui.device.GetNumber(...
                'clock', this.clock, ...
                'dWidthName', this.dWidthName, ...
                'dWidthUnit', this.dWidthUnit, ...
                'dWidthVal', this.dWidthVal, ...
                'cName', 'mod3-temp-sensor-frame-2', ...
                'lShowLabels', false, ...
                'config', uiConfig, ...
                'cLabel', 'Frame 2' ...
            );
        end
        
        function initUiFrame3(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-number', ...
                'config-mod3-temp-sensor-pt100.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiFrame3 = mic.ui.device.GetNumber(...
                'clock', this.clock, ...
                'dWidthName', this.dWidthName, ...
                'dWidthUnit', this.dWidthUnit, ...
                'dWidthVal', this.dWidthVal, ...
                'cName', 'mod3-temp-sensor-frame-3', ...
                'lShowLabels', false, ...
                'config', uiConfig, ...
                'cLabel', 'Frame 3' ...
            );
        end
        
        function initUiFrame4(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-number', ...
                'config-mod3-temp-sensor-pt100.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiFrame4 = mic.ui.device.GetNumber(...
                'clock', this.clock, ...
                'dWidthName', this.dWidthName, ...
                'dWidthUnit', this.dWidthUnit, ...
                'dWidthVal', this.dWidthVal, ...
                'cName', 'mod3-temp-sensor-frame-4', ...
                'lShowLabels', false, ...
                'config', uiConfig, ...
                'cLabel', 'Frame 4' ...
            );
        end
        
        function initUiFrame5(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-number', ...
                'config-mod3-temp-sensor-pt100.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiFrame5 = mic.ui.device.GetNumber(...
                'clock', this.clock, ...
                'dWidthName', this.dWidthName, ...
                'dWidthUnit', this.dWidthUnit, ...
                'dWidthVal', this.dWidthVal, ...
                'cName', 'mod3-temp-sensor-frame-5', ...
                'lShowLabels', false, ...
                'config', uiConfig, ...
                'cLabel', 'Frame 5' ...
            );
        end
        
        function initUiFrame6(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-number', ...
                'config-mod3-temp-sensor-pt100.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiFrame6 = mic.ui.device.GetNumber(...
                'clock', this.clock, ...
                'dWidthName', this.dWidthName, ...
                'dWidthUnit', this.dWidthUnit, ...
                'dWidthVal', this.dWidthVal, ...
                'cName', 'mod3-temp-sensor-frame-6', ...
                'lShowLabels', false, ...
                'config', uiConfig, ...
                'cLabel', 'Frame 6' ...
            );
        end
        
        
        
        
        
        function init(this)
            this.msg('init()');
            this.initUiReticleCam1();
            this.initUiReticleCam2();
            this.initUiFiducialCam1();
            this.initUiFiducialCam2();
            this.initUiFrame1();
            this.initUiFrame2();
            this.initUiFrame3();
            this.initUiFrame4();
            this.initUiFrame5();
            this.initUiFrame6();

            
        end
        
        
        
    end
    
    
end

