classdef PobTempSensors < mic.Base
    
    properties

        % {mic.ui.device.GetNumber 1x1}}
        uiFrame1
        
        % {mic.ui.device.GetNumber 1x1}}
        uiFrame2
        
        % {mic.ui.device.GetNumber 1x1}}
        uiFrame3
        
        % {mic.ui.device.GetNumber 1x1}}
        uiFrame4
        
        % {mic.ui.device.GetNumber 1x1}}
        uiFrame5
        
        % {mic.ui.device.GetNumber 1x1}}
        uiFrame6
        
        % {mic.ui.device.GetNumber 1x1}}
        uiFrame7
        
        % {mic.ui.device.GetNumber 1x1}}
        uiFrame8
        
        % {mic.ui.device.GetNumber 1x1}}
        uiFrame9
        
        % {mic.ui.device.GetNumber 1x1}}
        uiFrame10
        
        % {mic.ui.device.GetNumber 1x1}}
        uiFrame11
        
        % {mic.ui.device.GetNumber 1x1}}
        uiFrame12 
        
    end
    
    properties (SetAccess = private)
        
        dWidth = 300
        dHeight = 400
        
        cName = 'PobTempSensors'
        
    end
    
    properties (Access = private)
        
        clock
        
        hPanel
        
        dWidthName = 30
        dWidthUnit = 90
        
        configStageY
        configMeasPointVolts
        
    end
    
    methods
        
        function this = PobTempSensors(varargin)
            for k = 1 : 2: length(varargin)
                this.msg(sprintf('passed in %s', varargin{k}), this.u8_MSG_TYPE_VARARGIN_PROPERTY);
                if this.hasProp( varargin{k})
                    this.msg(sprintf(' settting %s', varargin{k}), this.u8_MSG_TYPE_VARARGIN_SET);
                    this.(varargin{k}) = varargin{k + 1};
                end
            end
            
            this.init();
        
        end
        
        
        function turnOn(this)
            
            this.uiFrame1.turnOn();
            this.uiFrame2.turnOn();
            this.uiFrame3.turnOn();
            this.uiFrame4.turnOn();
            this.uiFrame5.turnOn();
            this.uiFrame6.turnOn();
            this.uiFrame7.turnOn();
            this.uiFrame8.turnOn();
            this.uiFrame9.turnOn();
            this.uiFrame10.turnOn();
            this.uiFrame11.turnOn();
            this.uiFrame12.turnOn();
            
            
            
        end
        
        function turnOff(this)
            this.uiFrame1.turnOff();
            this.uiFrame2.turnOff();
            this.uiFrame3.turnOff();
            this.uiFrame4.turnOff();
            this.uiFrame5.turnOff();
            this.uiFrame6.turnOff();
            this.uiFrame7.turnOff();
            this.uiFrame8.turnOff();
            this.uiFrame9.turnOff();
            this.uiFrame10.turnOff();
            this.uiFrame11.turnOff();
            this.uiFrame12.turnOff();
            
            
        end
        
        function build(this, hParent, dLeft, dTop)
            
            this.hPanel = uipanel(...
                'Parent', hParent,...
                'Units', 'pixels',...
                'Title', 'POB Temp Sensors',...
                'Clipping', 'on',...
                'Position', mic.Utils.lt2lb([ ...
                dLeft ...
                dTop ...
                this.dWidth ...
                this.dHeight], hParent) ...
            );
        
			drawnow;            

            dTop = 20;
            dLeft = 10;
            dSep = 30;
            
            this.uiFrame1.build(this.hPanel, dLeft, dTop);
            dTop = dTop + 15 + dSep;
            
            this.uiFrame2.build(this.hPanel, dLeft, dTop);
            dTop = dTop + dSep;
            
            this.uiFrame3.build(this.hPanel, dLeft, dTop);
            dTop = dTop + dSep;
            
            this.uiFrame4.build(this.hPanel, dLeft, dTop);
            dTop = dTop + dSep;
            
            this.uiFrame5.build(this.hPanel, dLeft, dTop);
            dTop = dTop + dSep;
            
            this.uiFrame6.build(this.hPanel, dLeft, dTop);
            dTop = dTop + dSep;
            
            this.uiFrame7.build(this.hPanel, dLeft, dTop);
            dTop = dTop + dSep;
            
            this.uiFrame8.build(this.hPanel, dLeft, dTop);
            dTop = dTop + dSep;
            
            this.uiFrame9.build(this.hPanel, dLeft, dTop);
            dTop = dTop + dSep;
            
            this.uiFrame10.build(this.hPanel, dLeft, dTop);
            dTop = dTop + dSep;
            
            this.uiFrame11.build(this.hPanel, dLeft, dTop);
            dTop = dTop + dSep;
            
            this.uiFrame12.build(this.hPanel, dLeft, dTop);
            dTop = dTop + dSep;
            
           
            
        end
        
        function delete(this)
            
            this.msg('delete');
                        
            % Delete the figure
            
            if ishandle(this.hPanel)
                delete(this.hPanel);
            end
            
            
        end    
        
        
    end
    
    methods (Access = private)
                
         
        function initUiTemp1(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-number', ...
                'config-pob-temp-sensor.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiFrame1 = mic.ui.device.GetNumber(...
                'clock', this.clock, ...
                'dWidthName', this.dWidthName, ...
                'dWidthUnit', this.dWidthUnit, ...
                'cName', 'pob-temp-sensor-1', ...
                'config', uiConfig, ...
                'cLabel', '1' ...
            );
        end
        
        function initUiTemp2(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-number', ...
                'config-pob-temp-sensor.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiFrame2 = mic.ui.device.GetNumber(...
                'clock', this.clock, ...
                'dWidthName', this.dWidthName, ...
                'dWidthUnit', this.dWidthUnit, ...
                'cName', 'pob-temp-sensor-2', ...
                'lShowLabels', false, ...
                'config', uiConfig, ...
                'cLabel', '2' ...
            );
        end
        
        function initUiTemp3(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-number', ...
                'config-pob-temp-sensor.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiFrame3 = mic.ui.device.GetNumber(...
                'clock', this.clock, ...
                'dWidthName', this.dWidthName, ...
                'dWidthUnit', this.dWidthUnit, ...
                'cName', 'pob-temp-sensor-3', ...
                'lShowLabels', false, ...
                'config', uiConfig, ...
                'cLabel', '3' ...
            );
        end
        
        function initUiTemp4(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-number', ...
                'config-pob-temp-sensor.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiFrame4 = mic.ui.device.GetNumber(...
                'clock', this.clock, ...
                'dWidthName', this.dWidthName, ...
                'dWidthUnit', this.dWidthUnit, ...
                'cName', 'pob-temp-sensor-4', ...
                'lShowLabels', false, ...
                'config', uiConfig, ...
                'cLabel', '1' ...
            );
        end
        
        function initUiTemp5(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-number', ...
                'config-pob-temp-sensor.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiFrame5 = mic.ui.device.GetNumber(...
                'clock', this.clock, ...
                'dWidthName', this.dWidthName, ...
                'dWidthUnit', this.dWidthUnit, ...
                'cName', 'pob-temp-sensor-5', ...
                'lShowLabels', false, ...
                'config', uiConfig, ...
                'cLabel', '5' ...
            );
        end
        
        function initUiTemp6(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-number', ...
                'config-pob-temp-sensor.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiFrame6 = mic.ui.device.GetNumber(...
                'clock', this.clock, ...
                'dWidthName', this.dWidthName, ...
                'dWidthUnit', this.dWidthUnit, ...
                'cName', 'pob-temp-sensor-6', ...
                'lShowLabels', false, ...
                'config', uiConfig, ...
                'cLabel', '6' ...
            );
        end
        
        function initUiTemp7(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-number', ...
                'config-pob-temp-sensor.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiFrame7 = mic.ui.device.GetNumber(...
                'clock', this.clock, ...
                'dWidthName', this.dWidthName, ...
                'dWidthUnit', this.dWidthUnit, ...
                'cName', 'pob-temp-sensor-7', ...
                'lShowLabels', false, ...
                'config', uiConfig, ...
                'cLabel', '7' ...
            );
        end
        
        function initUiTemp8(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-number', ...
                'config-pob-temp-sensor.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiFrame8 = mic.ui.device.GetNumber(...
                'clock', this.clock, ...
                'dWidthName', this.dWidthName, ...
                'dWidthUnit', this.dWidthUnit, ...
                'cName', 'pob-temp-sensor-8', ...
                'lShowLabels', false, ...
                'config', uiConfig, ...
                'cLabel', '8' ...
            );
        end
        
        function initUiTemp9(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-number', ...
                'config-pob-temp-sensor.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiFrame9 = mic.ui.device.GetNumber(...
                'clock', this.clock, ...
                'dWidthName', this.dWidthName, ...
                'dWidthUnit', this.dWidthUnit, ...
                'cName', 'pob-temp-sensor-9', ...
                'lShowLabels', false, ...
                'config', uiConfig, ...
                'cLabel', '9' ...
            );
        end
        
        function initUiTemp10(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-number', ...
                'config-pob-temp-sensor.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiFrame10 = mic.ui.device.GetNumber(...
                'clock', this.clock, ...
                'dWidthName', this.dWidthName, ...
                'dWidthUnit', this.dWidthUnit, ...
                'cName', 'pob-temp-sensor-10', ...
                'lShowLabels', false, ...
                'config', uiConfig, ...
                'cLabel', '10' ...
            );
        end
        
        function initUiTemp11(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-number', ...
                'config-pob-temp-sensor.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiFrame11 = mic.ui.device.GetNumber(...
                'clock', this.clock, ...
                'dWidthName', this.dWidthName, ...
                'dWidthUnit', this.dWidthUnit, ...
                'cName', 'pob-temp-sensor-11', ...
                'lShowLabels', false, ...
                'config', uiConfig, ...
                'cLabel', '11' ...
            );
        end
        
        function initUiTemp12(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-number', ...
                'config-pob-temp-sensor.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiFrame12 = mic.ui.device.GetNumber(...
                'clock', this.clock, ...
                'dWidthName', this.dWidthName, ...
                'dWidthUnit', this.dWidthUnit, ...
                'cName', 'pob-temp-sensor-12', ...
                'lShowLabels', false, ...
                'config', uiConfig, ...
                'cLabel', '12' ...
            );
        end
        
        
        
        function init(this)
            this.msg('init()');
            this.initUiTemp1();
            this.initUiTemp2();
            this.initUiTemp3();
            this.initUiTemp4();
            this.initUiTemp5();
            this.initUiTemp6();
            this.initUiTemp7();
            this.initUiTemp8();
            this.initUiTemp9();
            this.initUiTemp10();
            this.initUiTemp11();
            this.initUiTemp12();
            
        end
        
        
        
    end
    
    
end

