classdef VibrationIsolationSystem < mic.Base
    
    properties
        
        
        % These are the UI for activating the hardware that gives the 
        % software real data
        
        % {mic.ui.device.GetSetLogical 1x1}
        uiCommGalil
       
        % {mic.ui.device.GetSetNumber 1x1}
        uiStage1
        
        % {mic.ui.device.GetSetNumber 1x1}
        uiStage2
        
        % {mic.ui.device.GetSetNumber 1x1}
        uiStage3
        
        % {mic.ui.device.GetSetNumber 1x1}
        uiStage4
        
        % {mic.ui.device.GetNumber 1x1}
        uiEncoder1
        uiEncoder2
        uiEncoder3
        uiEncoder4
        
       
        
    end
    
    properties (Access = private)
        
        clock
        dWidth = 520
        dHeight = 310
        hFigure
        
        dWidthName = 70
        dWidthPadName = 29
        dWidthPadUnitEncoder = 177
                
    end
    
    properties (SetAccess = private)
        
        cName = 'vibration-isolation-system'
    end
    
    methods
        
        function this = VibrationIsolationSystem(varargin)
            for k = 1 : 2: length(varargin)
                this.msg(sprintf('passed in %s', varargin{k}), this.u8_MSG_TYPE_VARARGIN_PROPERTY);
                if this.hasProp( varargin{k})
                    this.msg(sprintf(' settting %s', varargin{k}), this.u8_MSG_TYPE_VARARGIN_SET);
                    this.(varargin{k}) = varargin{k + 1};
                end
            end
            
            this.init();
        
        end
        
        function connectDataTranslationMeasurPoint(this, comm)
            device1 = GetNumberFromDataTranslationMeasurPoint(...
                comm, ...
                GetNumberFromDataTranslationMeasurPoint.cTYPE_TEMP_RTD, ...
                11 ...
            );
            device2 = GetNumberFromDataTranslationMeasurPoint(...
                comm, ...
                GetNumberFromDataTranslationMeasurPoint.cTYPE_TEMP_RTD, ...
                12 ...
            );
            device3 = GetNumberFromDataTranslationMeasurPoint(...
                comm, ...
                GetNumberFromDataTranslationMeasurPoint.cTYPE_TEMP_RTD, ...
                13 ...
            );
            device4 = GetNumberFromDataTranslationMeasurPoint(...
                comm, ...
                GetNumberFromDataTranslationMeasurPoint.cTYPE_TEMP_RTD, ...
                14 ...
            );
            this.uiVisTempSensors.uiFrame1.setDevice(device1);
            this.uiVisTempSensors.uiFrame2.setDevice(device2);
            this.uiVisTempSensors.uiFrame3.setDevice(device3);
            this.uiVisTempSensors.uiFrame4.setDevice(device4);
            
            this.uiVisTempSensors.uiFrame1.turnOn();
            this.uiVisTempSensors.uiFrame2.turnOn();
            this.uiVisTempSensors.uiFrame3.turnOn();
            this.uiVisTempSensors.uiFrame4.turnOn();
        end
        
        function disconnectDataTranslationMeasurPoint(this)
            
        end
        
        function connectGalil(this, comm)
            
            device1 = bl12014.device.GetSetNumberFromStage(comm, 0);
            device2 = bl12014.device.GetSetNumberFromStage(comm, 1);
            device3 = bl12014.device.GetSetNumberFromStage(comm, 2);
            device4 = bl12014.device.GetSetNumberFromStage(comm, 3);
            
            this.uiStage1.setDevice(device1);
            this.uiStage2.setDevice(device2);
            this.uiStage3.setDevice(device3);
            this.uiStage4.setDevice(device4);
            
            this.uiStage1.turnOn();
            this.uiStage2.turnOn();
            this.uiStage3.turnOn();
            this.uiStage4.turnOn();
            
            % FIXME
            % Need to wire in the encoders
            
            %{
            device1 = bl12014.device.GetSetNumberFromStage(comm, 0);
            device2 = bl12014.device.GetSetNumberFromStage(comm, 1);
            device3 = bl12014.device.GetSetNumberFromStage(comm, 2);
            device4 = bl12014.device.GetSetNumberFromStage(comm, 3);
            
            this.uiEncoder1.setDevice(device1);
            this.uiEncoder2.setDevice(device2);
            this.uiEncoder3.setDevice(device3);
            this.uiEncoder4.setDevice(device4);
            
            this.uiEncoder1.turnOn();
            this.uiEncoder2.turnOn();
            this.uiEncoder3.turnOn();
            this.uiEncoder4.turnOn();
            %}
            
            
        end
        
        function disconnectGalil(this)
            this.uiStage1.turnOff();
            this.uiStage2.turnOff();
            this.uiStage3.turnOff();
            this.uiStage4.turnOff();
            
            this.uiStage1.setDevice([]);
            this.uiStage2.setDevice([]);
            this.uiStage3.setDevice([]);
            this.uiStage4.setDevice([]);
        end
        
        
        function build(this)
            
            if ishghandle(this.hFigure)
                % Bring to front
                figure(this.hFigure);
                return
            end
            
            dScreenSize = get(0, 'ScreenSize');
            
            this.hFigure = figure( ...
                'NumberTitle', 'off', ...
                'MenuBar', 'none', ...
                'Name', 'Vibration Isolation System Control', ...
                'Position', [ ...
                    (dScreenSize(3) - this.dWidth)/2 ...
                    (dScreenSize(4) - this.dHeight)/2 ...
                    this.dWidth ...
                    this.dHeight ...
                 ],... % left bottom width height
                'Resize', 'off', ...
                'HandleVisibility', 'on', ... % lets close all close the figure
                'Visible', 'on',...
                'CloseRequestFcn', @this.onFigureCloseRequest ...
            );
                        
            drawnow;

            dTop = 10;
            dLeft = 10;
            dSep = 30;
            
                       
            this.uiCommGalil.build(this.hFigure, dLeft, dTop);
            dTop = dTop + 15 + dSep;
                       
            this.uiStage1.build(this.hFigure, dLeft, dTop);
            dTop = dTop + dSep;
            
            this.uiStage2.build(this.hFigure, dLeft, dTop);
            dTop = dTop + dSep;
            
            this.uiStage3.build(this.hFigure, dLeft, dTop);
            dTop = dTop + dSep;
            
            this.uiStage4.build(this.hFigure, dLeft, dTop);
            dTop = dTop + dSep;
            
            
            this.uiEncoder1.build(this.hFigure, dLeft, dTop);
            dTop = dTop + dSep;
            
            this.uiEncoder2.build(this.hFigure, dLeft, dTop);
            dTop = dTop + dSep;
            
            this.uiEncoder3.build(this.hFigure, dLeft, dTop);
            dTop = dTop + dSep;
            
            this.uiEncoder4.build(this.hFigure, dLeft, dTop);
            dTop = dTop + dSep;
            
            

            
        end
        
        function delete(this)
            
            this.msg('delete');
                        
            % Delete the figure
            
            if ishandle(this.hFigure)
                delete(this.hFigure);
            end
            
            
        end    
        
        
        
    end
    
    methods (Access = private)
        
         function onFigureCloseRequest(this, src, evt)
            this.msg('M141Control.closeRequestFcn()');
            delete(this.hFigure);
            this.hFigure = [];
         end
         
         
         function initUiEncoder1(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-number', ...
                'config-vibration-isolation-system-encoder-1.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiEncoder1 = mic.ui.device.GetNumber(...
                'clock', this.clock, ...
                'dWidthName', this.dWidthName, ...
                'dWidthPadName', this.dWidthPadName, ...
                'dWidthPadUnit', this.dWidthPadUnitEncoder, ...
                'lShowLabels', false, ...
                'cName', sprintf('%s-encoder-1', this.cName), ...
                'config', uiConfig, ...
                'cLabel', 'Encoder 1' ...
            );
         end
         
         function initUiEncoder2(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-number', ...
                'config-vibration-isolation-system-encoder-2.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiEncoder2 = mic.ui.device.GetNumber(...
                'clock', this.clock, ...
                'dWidthName', this.dWidthName, ...
                'dWidthPadName', this.dWidthPadName, ...
                'dWidthPadUnit', this.dWidthPadUnitEncoder, ...
                'lShowLabels', false, ...
                'cName', sprintf('%s-encoder-2', this.cName), ...
                'config', uiConfig, ...
                'cLabel', 'Encoder 2' ...
            );
         end
         
         function initUiEncoder3(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-number', ...
                'config-vibration-isolation-system-encoder-3.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiEncoder3 = mic.ui.device.GetNumber(...
                'clock', this.clock, ...
                'dWidthName', this.dWidthName, ...
                'dWidthPadName', this.dWidthPadName, ...
                'dWidthPadUnit', this.dWidthPadUnitEncoder, ...
                'lShowLabels', false, ...
                'cName', sprintf('%s-encoder-3', this.cName), ...
                'config', uiConfig, ...
                'cLabel', 'Encoder 3' ...
            );
         end
         
         function initUiEncoder4(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-number', ...
                'config-vibration-isolation-system-encoder-4.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiEncoder4 = mic.ui.device.GetNumber(...
                'clock', this.clock, ...
                'dWidthName', this.dWidthName, ...
                'dWidthPadName', this.dWidthPadName, ...
                'dWidthPadUnit', this.dWidthPadUnitEncoder, ...
                'lShowLabels', false, ...
                'cName', sprintf('%s-encoder-4', this.cName), ...
                'config', uiConfig, ...
                'cLabel', 'Encoder 4' ...
            );
         end
        
         
         
               
        
        function initUiStage1(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-set-number', ...
                'config-vibration-isolation-system-stage.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiStage1 = mic.ui.device.GetSetNumber(...
                'clock', this.clock, ...
                'dWidthName', this.dWidthName, ...
                'dWidthPadName', this.dWidthPadName, ...
                'lShowLabels', false, ...
                'lShowRange', false, ...
                'lShowStores', false, ...
                'cName', sprintf('%s-1', this.cName), ...
                'config', uiConfig, ...
                'cLabel', 'Motor 1' ...
            );
        end
        
        function initUiStage2(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-set-number', ...
                'config-vibration-isolation-system-stage.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiStage2 = mic.ui.device.GetSetNumber(...
                'clock', this.clock, ...
                'dWidthName', this.dWidthName, ...
                'dWidthPadName', this.dWidthPadName, ...
                'lShowLabels', false, ...
                'lShowRange', false, ...
                'lShowStores', false, ...
                'cName', sprintf('%s-2', this.cName), ...
                'config', uiConfig, ...
                'cLabel', 'Motor 2' ...
            );
        end
        
        function initUiStage3(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-set-number', ...
                'config-vibration-isolation-system-stage.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiStage3 = mic.ui.device.GetSetNumber(...
                'clock', this.clock, ...
                'dWidthName', this.dWidthName, ...
                'dWidthPadName', this.dWidthPadName, ...
                'lShowLabels', false, ...
                'lShowRange', false, ...
                'lShowStores', false, ...
                'cName', sprintf('%s-3', this.cName), ...
                'config', uiConfig, ...
                'cLabel', 'Motor 3' ...
            );
        end
        
        function initUiStage4(this)
            
            cPathConfig = fullfile(...
                bl12014.Utils.pathUiConfig(), ...
                'get-set-number', ...
                'config-vibration-isolation-system-stage.json' ...
            );
        
            uiConfig = mic.config.GetSetNumber(...
                'cPath',  cPathConfig ...
            );
            
            this.uiStage4 = mic.ui.device.GetSetNumber(...
                'clock', this.clock, ...
                'dWidthName', this.dWidthName, ...
                'dWidthPadName', this.dWidthPadName, ...
                'lShowLabels', false, ...
                'lShowRange', false, ...
                'lShowStores', false, ...
                'cName', sprintf('%s-4', this.cName), ...
                'config', uiConfig, ...
                'cLabel', 'Motor 4' ...
            );
        end
        
        function initUiCommGalil(this)
            
            
            % Configure the mic.ui.common.Toggle instance
            ceVararginCommandToggle = {...
                'cTextTrue', 'Disconnect', ...
                'cTextFalse', 'Connect' ...
            };

            this.uiCommGalil = mic.ui.device.GetSetLogical(...
                'clock', this.clock, ...
                'ceVararginCommandToggle', ceVararginCommandToggle, ...
                'dWidthName', 130, ...
                'lShowLabels', false, ...
                'lShowDevice', false, ...
                'lShowInitButton', false, ...
                'cName', sprintf('%s-galil-dmc-4143', this.cName), ...
                'cLabel', 'Galil DMC 4143' ...
            );
        
        end
        
        
        

        function init(this)
            this.msg('init');
            
            this.initUiCommGalil();
            this.initUiStage1();
            this.initUiStage2();
            this.initUiStage3();
            this.initUiStage4();
            
            this.initUiEncoder1();
            this.initUiEncoder2();
            this.initUiEncoder3();
            this.initUiEncoder4();
        end
        
        
        
    end
    
    
end

