try
    purge
end


[cDirThis, cName, cExt] = fileparts(mfilename('fullpath'));

% bl12014 pkg
cDirBl12014 = fullfile(cDirThis, '..', 'src');
addpath(genpath(cDirBl12014));

strcmpi(...
    bl12014.getNameOfReticleField(...
        'row', 6, ...
        'col', 6 ...
    ), ...
    'F2X' ...
)

strcmpi(...
    bl12014.getNameOfReticleField(...
        'row', 6, ...
        'col', 7 ...
    ), ...
    'F2X Cleave' ...
)


strcmpi(...
    bl12014.getNameOfReticleField(...
        'row', 1, ...
        'col', 19 ...
    ), ...
    'Clear' ...
)