% textscan test

cText = '1.2,2019-12-20 14:20:21';
cFormat = '%f%{yyyy-MM-dd HH:mm:ss}D';
ceData = textscan(...
    cText, cFormat, -1, ...
    'delimiter', ',' ...
    ...'whitespace', '' ...
)



cText = 'chris,bob_hello,ryan';
cFormat = '%q%q%q';
cFormat = repmat('%s', 1, 3);
ceData = textscan(...
    cText, cFormat, 1, ...
    'delimiter', ',' ...
    ...'whitespace', '' ...
)