[cDirThis, cName, cExt] = fileparts(mfilename('fullpath'));

% bl12014 pkg
cDirBl12014 = fullfile(cDirThis, '..', 'src');
addpath(genpath(cDirBl12014));

% dependencies
cDirVendor = fullfile(cDirThis, '..', 'vendor');
cDirCnanders = fullfile(cDirVendor, 'github', 'cnanders');

cDirMic = fullfile(...
    cDirCnanders, ...
    'matlab-instrument-control', ...
    'src'...
);
addpath(genpath(cDirMic));

cDirMicronixMMC103 = fullfile(...
    cDirCnanders, ...
    'matlab-micronix-mmc-103', ...
    'src' ...
);
addpath(genpath(cDirMicronixMMC103));

cDirNewFocusModel8742 = fullfile(...
    cDirCnanders, ...
    'matlab-newfocus-model-8742', ...
    'src' ...
);
addpath(genpath(cDirNewFocusModel8742));

purge

app = bl12014.App();
app.build()


 

