try 
    purge
catch mE
end

[cDirThis, cName, cExt] = fileparts(mfilename('fullpath'));
addpath(genpath(fullfile(cDirThis, '..', '..', 'src')));
addpath(genpath(fullfile(cDirThis, '..', '..', 'mpm-packages')));


clock = mic.Clock('master');
uiClock = mic.ui.Clock(clock);
hardware = bl12014.Hardware('clock', clock);

uiBeamline = bl12014.ui.Beamline( ...
    'clock', clock, ...
    'hardware', hardware, ...
    'uiClock', uiClock ...
);  

uiScannerM142 = bl12014.ui.Scanner(...
    'fhGetNPoint', @() hardware.getNPointMA(), ...
    'cName', 'm142', ...
    'clock', clock, ...
    'uiClock', uiClock ...
);

exposures = bl12014.DCTExposures();

uiFluxDensity = bl12014.ui.DCTFluxDensity(...
    'clock', clock, ...
    'hardware', hardware, ...
    'uiClock', uiClock, ...
    'exposures', exposures, ...
    'uiBeamline', uiBeamline, ...
    'uiScannerM142', uiScannerM142 ...
);

ui = bl12014.ui.ScannerPlotDCT(...
    'uiClock', uiClock, ...
    'fhGetWidthOfAperture', @() uiFluxDensity.uiDiode.uiPopupAperture.get().dWidth * 1e-3, ...
    'fhGetHeightOfAperture', @() uiFluxDensity.uiDiode.uiPopupAperture.get().dWidth * 1e-3, ...
    'fhGetWavetables', @() uiScannerM142.uiNPointLC400.getWavetables(), ...
    'fhGetActive', @() uiScannerM142.uiNPointLC400.uiGetSetLogicalActive.get() ...
);


dWidth = 200;
dHeight = 200;
dScreenSize = get(0, 'ScreenSize');
h = figure(...
    'Position', [ ...
        (dScreenSize(3) - dWidth)/2 ...
        (dScreenSize(4) - dHeight)/2 ...
        dWidth ...
        dHeight ...
    ] ...
);

ui.build(h, 10, 10);





 
