try 
    purge
catch mE
end

[cDirThis, cName, cExt] = fileparts(mfilename('fullpath'));
addpath(genpath(fullfile(cDirThis, '..', '..', 'src')));
addpath(genpath(fullfile(cDirThis, '..', '..', 'mpm-packages')));


clock = mic.Clock('master');
uiClock = mic.ui.Clock(clock);
hardware = bl12014.Hardware('clock', clock);

uiBeamline = bl12014.ui.Beamline( ...
    'clock', clock, ...
    'hardware', hardware, ...
    'uiClock', uiClock ...
); 

ui = bl12014.ui.DCT(...
   'uiBeamline', uiBeamline, ...
   'hardware', hardware, ...
   'clock', clock ...
);


dWidth = 1750;
dHeight = 900;
dScreenSize = get(0, 'ScreenSize');
h = figure(...
    'Position', [ ...
        (dScreenSize(3) - dWidth)/2 ...
        (dScreenSize(4) - dHeight)/2 ...
        dWidth ...
        dHeight ...
    ] ...
);

ui.build(h, 100, 10);