try
    purge
end

[cDirThis, cName, cExt] = fileparts(mfilename('fullpath'));

% src
cDirBl12014 = fullfile(cDirThis, '..', '..', 'src');
addpath(genpath(cDirBl12014));

% mpm dependencies
addpath(genpath(fullfile(cDirThis, '..', '..', 'mpm-packages')));

hardware = bl12014.Hardware();
waferExposureHistory = bl12014.WaferExposureHistory();
waferExposureHistory.addFakeExposures();


clock = mic.Clock('Master');
uiClock = mic.ui.Clock(clock);

uiReticle = bl12014.ui.Reticle(...
    'clock', clock, ...
    'hardware', hardware, ...
    'uiClock', uiClock ...
);

uiScannerMA = bl12014.ui.Scanner(...
    'fhGetNPoint', @() this.hardware.getNPointMA(), ...
    'cName', 'ma', ...
    'clock', clock, ...
    'uiClock', uiClock ...
);

uiScannerM142 = bl12014.ui.Scanner(...
    'fhGetNPoint', @() this.hardware.getNPointMA(), ...
    'cName', 'm142', ...
    'clock', clock, ...
    'uiClock', uiClock ...
);

uiBeamline = bl12014.ui.Beamline(...
    'hardware', hardware, ...
    'uiClock', uiClock, ...
    'clock', clock ...
);

ui = bl12014.ui.TuneFluxDensity(...
    'clock', clock, ...
    'hardware', hardware, ...
    'uiGratingTiltX', uiBeamline.uiGratingTiltX, ...
    'uiClock', uiClock, ...
    'uiReticle', uiReticle, ...
    'uiScannerMA', uiScannerMA, ...
    'uiScannerM142', uiScannerM142, ...
    'waferExposureHistory', waferExposureHistory ...
);



dWidth = 800;
dHeight = 820;

dScreenSize = get(0, 'ScreenSize');
h = figure(...
    'Position', [ ...
        (dScreenSize(3) - dWidth)/2 ...
        (dScreenSize(4) - dHeight)/2 ...
        dWidth ...
        dHeight ...
    ] ...
);

ui.build(h, 10, 10);



 

