try 
    purge
catch mE
end

[cDirThis, cName, cExt] = fileparts(mfilename('fullpath'));
addpath(genpath(fullfile(cDirThis, '..', '..', 'src')));
addpath(genpath(fullfile(cDirThis, '..', '..', 'mpm-packages')));


clock = mic.Clock('Master');
hardware = bl12014.Hardware('clock', clock);

waferExposureHistory = bl12014.WaferExposureHistory();
waferExposureHistory.addFakeExposures();

clock = mic.Clock('Master');
uiClock = mic.ui.Clock(clock);

uiReticle = bl12014.ui.Reticle(...
    'clock', clock, ...
    'hardware', hardware, ...
    'uiClock', uiClock ...
);

ui = bl12014.ui.FluxDensityComparison(...
    'clock', clock, ...
    'hardware', hardware, ...
    'uiClock', uiClock, ...
    'uiReticle', uiReticle ...
);


dWidth = 800;
dHeight = 820;

dScreenSize = get(0, 'ScreenSize');
h = figure(...
    'Position', [ ...
        (dScreenSize(3) - dWidth)/2 ...
        (dScreenSize(4) - dHeight)/2 ...
        dWidth ...
        dHeight ...
    ] ...
);

ui.build(h, 10, 10);



 

