try 
    purge
catch mE
end

[cDirThis, cName, cExt] = fileparts(mfilename('fullpath'));
addpath(genpath(fullfile(cDirThis, '..', '..', 'src')));
addpath(genpath(fullfile(cDirThis, '..', '..', 'mpm-packages')));


clock = mic.Clock('Master');
hardware = bl12014.Hardware('clock', clock);
uiClock = mic.ui.Clock(clock);

uiScannerM142 = bl12014.ui.Scanner(...
    'fhGetNPoint', @() hardware.getNPointMA(), ...
    'cName', 'm142', ...
    'clock', clock, ...
    'uiClock', uiClock ...
);

uiBeamline = bl12014.ui.Beamline(...
    'hardware', hardware, ...
    'uiClock', uiClock, ...
    'clock', clock ...
);

ui = bl12014.ui.DCTFluxDensity(...
    'clock', clock, ...
    'uiClock', uiClock, ...
    'hardware', hardware, ...
    'uiGratingTiltX', uiBeamline.uiGratingTiltX, ...
    'uiScannerM142', uiScannerM142 ...
);

dWidth = 800;
dHeight = 820;

dScreenSize = get(0, 'ScreenSize');
h = figure(...
    'Position', [ ...
        (dScreenSize(3) - dWidth)/2 ...
        (dScreenSize(4) - dHeight)/2 ...
        dWidth ...
        dHeight ...
    ] ...
);

ui.build(h, 10, 10);



 

