try 
    purge
catch mE
end

[cDirThis, cName, cExt] = fileparts(mfilename('fullpath'));
addpath(genpath(fullfile(cDirThis, '..', '..', 'src')));
addpath(genpath(fullfile(cDirThis, '..', '..', 'mpm-packages')));


clock = mic.Clock('Master');
hardware = bl12014.Hardware('clock', clock);


ui = bl12014.ui.DCT2Diode(...
    'cName', 'dct2-diode-1', ...
    'cTitle', 'Diode 1', ...
    'fhSetSensitivity', @(dLevel) hardware.getSR570DCT1().setSensitivity(dLevel), ...
    'fhGetVolts', @() hardware.getDataTranslation().getScanDataOfChannel(33), ...
    'clock', clock ...
);

dWidth = 800;
dHeight = 500;
dScreenSize = get(0, 'ScreenSize');
h = figure(...
    'Position', [ ...
        (dScreenSize(3) - dWidth)/2 ...
        (dScreenSize(4) - dHeight)/2 ...
        dWidth ...
        dHeight ...
    ] ...
);

ui.build(h, 10, 10);


 

