try 
    purge
catch mE
end

[cDirThis, cName, cExt] = fileparts(mfilename('fullpath'));
addpath(genpath(fullfile(cDirThis, '..', '..', 'src')));
addpath(genpath(fullfile(cDirThis, '..', '..', 'mpm-packages')));


clock = mic.Clock('Master');

exposures = bl12014.DCTExposures();
exposures.addFakeExposures();
exposures.addFakePre();
exposures.addFakeScan();

ui = bl12014.ui.DCTWaferAxes(...
    'clock', clock, ...
    'fhGetIsShutterOpen', @() false, ...
    'fhGetXOfWafer', @() -10e-3, ...
    'fhGetYOfWafer', @() 10e-3, ...
    'fhGetXOfAperture', @() 10e-3, ...
    'fhGetYOfAperture', @() 5e-3, ...
    'exposures', exposures, ...
    'cName', 'test' ...
);


dWidth = 800;
dHeight = 700;

dScreenSize = get(0, 'ScreenSize');
            
h = figure( ...
    'Position', [ ...
        (dScreenSize(3) - dWidth)/2 ...
        (dScreenSize(4) - dHeight)/2 ...
        dWidth ...
        dHeight ...
     ] ...
);
% set(h,'renderer','zbuffer')
ui.build(h, 10, 10);

 

