try
    purge
end

[cDirThis, cName, cExt] = fileparts(mfilename('fullpath'));

% bl12014 pkg
cDirBl12014 = fullfile(cDirThis, '..', '..', 'src');
addpath(genpath(cDirBl12014));

% dependencies
cDirVendor = fullfile(cDirThis, '..', '..', 'vendor');

addpath(genpath(fullfile(cDirVendor, 'github', 'cnanders', 'matlab-instrument-control', 'src')));


clock = mic.Clock('master');
hardware = bl12014.Hardware();
uiClock = mic.ui.Clock(clock);


uiReticle = bl12014.ui.Reticle(...
    'clock', clock, ...
    'hardware', hardware, ...
    'uiClock', uiClock ...
);
uiWafer = bl12014.ui.Wafer(...
    'clock', clock, ...
    'hardware', hardware, ...
    'uiClock', uiClock ...
);
uiShutter = bl12014.ui.Shutter( ...
    'clock', clock, ...
    'hardware', hardware, ...
    'uiClock', uiClock ...
);
uiBeamline = bl12014.ui.Beamline( ...
    'clock', clock, ...
    'hardware', hardware, ...
    'uiClock', uiClock ...
);  
uiScannerMA = bl12014.ui.Scanner(...
    'cName', 'ma', ...
    'clock', clock, ...
    'uiClock', uiClock ...
);
uiScannerM142 = bl12014.ui.Scanner(...
    'cName', 'm142', ...
    'clock', clock, ...
    'uiClock', uiClock ...
);

waferExposureHistory = bl12014.WaferExposureHistory();
waferExposureHistory.addFakeExposures();

ui = bl12014.ui.Scan(...
    'clock', clock, ...
    'uiClock', uiClock, ...
    'hardware', hardware, ...
    'waferExposureHistory', waferExposureHistory, ...
    'uiShutter', uiShutter, ...
    'uiReticle', uiReticle, ...
    'uiWafer', uiWafer, ...
    'uiScannerMA', uiScannerMA, ...
    'uiScannerM142', uiScannerM142 ...
);

dWidth = 1650;
dHeight = 900;
dScreenSize = get(0, 'ScreenSize');
h = figure(...
    'Position', [ ...
        (dScreenSize(3) - dWidth)/2 ...
        (dScreenSize(4) - dHeight)/2 ...
        dWidth ...
        dHeight ...
    ] ...
);



ui.build(h, 10, 10);

%{
cb = @(src, evt) (fprintf('x %1.3f, y %1.3f \n', evt.stData.dX, evt.stData.dY));
addlistener(ui, 'eClickField', cb);
%}


 

