try 
    purge
catch mE
end

[cDirThis, cName, cExt] = fileparts(mfilename('fullpath'));
addpath(genpath(fullfile(cDirThis, '..', '..', 'src')));
addpath(genpath(fullfile(cDirThis, '..', '..', 'mpm-packages')));

purge

clock = mic.Clock('Master');
hardware = bl12014.Hardware('clock', clock);

ui = bl12014.ui.WinCam(...
    'hardware', hardware, ...
    'uiClock', clock, ...
    'cName', 'Uniformity Camera', ...
    'clock', clock ...
);

ui2 = bl12014.ui.WinCam(...
    'hardware', hardware, ...
    'uiClock', clock, ...
    'cName', 'test Camera', ...
    'clock', clock ...
);


dWidth = 1600;
dHeight = 600;
dScreenSize = get(0, 'ScreenSize');

h = figure(...
    'Position', [ ...
        (dScreenSize(3) - dWidth)/2 ...
        (dScreenSize(4) - dHeight)/2 ...
        dWidth ...
        dHeight ...
    ] ...
);


ui.build(h, 10, 10);
ui2.build(h, 510, 10);





 

